---
driver_plugin: vagrant

platforms:
  - name: debian-7.6
    driver_config:
      box: chef/debian-7.6
  - name: centos-6.5
    driver_config:
      box: chef/centos-6.5
  - name: ubuntu-14.04
    driver_config:
        box: chef/ubuntu-14.04

suites:
  - name: create
    run_list:
      - recipe[lvm]
      - recipe[fake::create]
      - recipe[fake::resize]
