AlignParameters:
  Enabled: false

Encoding:
  Enabled: false

LineLength:
  Max: 200

MethodLength:
  Max: 30

CyclomaticComplexity:
  Max: 16

ParameterLists:
  Enabled: false

ClassLength:
  Max: 117
