---
name: "Lint & Unit Test"

"on":
  pull_request:
  push:
    branches: [main]

jobs:
  lint-unit:
    uses: sous-chefs/.github/.github/workflows/lint-unit.yml@2.0.4

  integration:
    needs: lint-unit
    runs-on: macos-10.15
    strategy:
      matrix:
        os:
          # - almalinux-8
          - amazonlinux-2
          - debian-10
          - debian-11
          - centos-7
          - centos-stream-8
          - fedora-latest
          - ubuntu-1804
          - ubuntu-2004
          # - ubuntu-2204
          # - rockylinux-8
        suite:
          - create
          - remove
          - create-thin
          - resize
          - resize-thin
          - resize-thin-pool-meta-data
      fail-fast: false

    steps:
      - name: Check out code
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - name: Install Chef
        uses: actionshub/chef-install@2.0.4
      - name: test-kitchen
        uses: actionshub/test-kitchen@2.1.0
        env:
          CHEF_LICENSE: accept-no-persist
        with:
          suite: ${{ matrix.suite }}
          os: ${{ matrix.os }}
